# Generated by Django 3.1.7 on 2021-02-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('place', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=120)),
            ],
        ),
    ]
