# Generated by Django 3.1.6 on 2021-02-24 18:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('surname', models.CharField(max_length=200, verbose_name='Surname')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Company')),
                ('direction', models.CharField(max_length=200, verbose_name='Direction')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone')),
                ('contact_ids', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bioinformatica.client')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('place', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2021, 2, 24, 15, 41, 8, 815639), verbose_name='Create date')),
                ('description', models.TextField(verbose_name='Description')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bioinformatica.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='project_ids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bioinformatica.project'),
        ),
    ]
