# Generated by Django 3.1.7 on 2021-02-24 00:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 0, 15, 28, 146737, tzinfo=utc), verbose_name='date published'),
        ),
    ]
