# Generated by Django 3.1.6 on 2021-02-24 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_id', models.CharField(max_length=120)),
                ('attribute_type', models.CharField(choices=[('TYPE1', 'Type 1'), ('TYPE2', 'Type 2'), ('TYPE3', 'Type 3')], default='T1', max_length=5)),
                ('attribute_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 15, 46, 15, 609620), verbose_name='Create date'),
        ),
    ]
