# Generated by Django 3.1.7 on 2021-02-24 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatica', '0002_auto_20210224_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 19, 8, 54, 703387), verbose_name='Create date'),
        ),
    ]
