# Generated by Django 3.1.7 on 2021-02-24 00:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bioinformatica', '0002_auto_20210223_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 0, 34, 31, 33352, tzinfo=utc), verbose_name='date published'),
        ),
    ]
